hidden_layers: [100, 100, 120, 1]
hidden_activations: ["tanh", "tanh", "tanh", "tanh"]
filters: [128, 128, 128, 128]
batch_size: 64
n_epochs: 5
learning_rate: .0002
momentum: .7
model_type: "dnnregressor_analytic"
optimizer: "adam"
log: True
loss: "huber"