hidden_layers: [100, 100, 120, 1]
hidden_activations: ["tanh", "tanh", "tanh", "linear"]
filters: [128, 128, 128, 128]
batch_size: 1024
n_epochs: 20
learning_rate: .002 # I think was originally 0.0002
momentum: .7
model_type: "dnnregressor"
optimizer: "adam"
log: True
loss: "huber"
gpu_x7: '1'