n_choices: 2
n_parameter_sets: 1000
n_reps: 1
n_experiments: 100
perturbation_sizes: [[0.05, 0.1, 0.2, 0.4],
                     [0.05, 0.1, 0.2, 0.4],
                     [0.05, 0.1, 0.2, 0.25],
                     [0.05, 0.1, 0.2, 0.4]]
n_cpus: 'all'
n_bins: 256
bin_dt: 0.04
